### ISSUE TITLE
Run plugins asynchronously (EditorConfig and other plugins slowing down Code)

### ISSUE THREAD

**Issue by ghost** [elementary/code#1314]
### What Happened?

Some plugins slow down Code a lot, to the point that Code is barely usable in weak CPUs.

### Steps to Reproduce

In a weak CPU (like a Raspberry Pi or a Chromebook):
1. Get Code
2. Enable some plugins
3. See slowdown.

### Expected Behavior

This does not happen in heavier text editors that do more stuff like VSCode because each extension runs in its own thread. Maybe we could get some ideas from them?

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Chromebook: Intel Celeron N4020 4GB RAM 32GB eMMC.

**Comment by jeremypw** [comment]
Would be possible to identify a plugin that slows Code down particularly badly or is it a combination of plugins?

**Comment by aitor-gomila** [comment]
I don't think a particular plugin is the problem. There are always memory leaks. However one slow tab on Chrome doesn't slow it down or crash it, same with VSCode. So my opinion is the problem is plugins run synchronously with the code editor.

Even when all plugins are disabled, Code runs worse than Gedit and other editors, and is marked as "consuming lots of energy" by elementary. Don't know why.

**Comment by jeremypw** [comment]
The Git integration (which is in the main code) probably uses significant power for a large repository.

**Comment by jeremypw** [comment]
You could try turning off "Autosave" to stop documents continually being saved while being edited.

**Comment by aitor-gomila** [comment]
I'll try that

**Comment by aitor-gomila** [comment]
Disabling the situation makes the text editor run much smoother. However in my opinion Code should remain simple in its core and extend itself with plugins (so no Git integration in the core for example)

**Comment by jeremypw** [comment]
What do you mean by "disabling the situation"?  Are you working on a git repository? The git integration should not consume power if you are not.  We can look for inefficiencies in the git integration.  Code is targeted at editing code in git repositories so that does need to be efficient.  Improving git integration completeness is one of our aims.

**Comment by jeremypw** [comment]
We could look at options to disable some aspects of git integration like real time updating the git status of each line in the document which slower machines might struggle with.

**Comment by aitor-gomila** [comment]
Closing tabs is also slow (takes something like half a second or 1 second). It shouldn't be this way, even when plugins are enabled.

**Comment by jeremypw** [comment]
@aitor-gomila How many tabs are we talking about? Or is it half a second *per tab*?  How large a document? I find closing a single tab containing <2000 lines in the master version virtually instantaneous with an SSD. A certain amount of checking goes on before the tab closes.

**Comment by aitor-gomila** [comment]
Maybe more like 1-2 seconds per tab. Documents aren't longer than 200 lines. It's a chromebook with an eMMC. I know an SSD is recommended but the OS in general works fine, blazingly fast. It's just the Code app.

**Comment by jeremypw** [comment]
@aitor-gomila Thanks for the investigation!  So it looks like the editorconfig plugin is mainly responsible?  I'll look at the code to see if there is an obvious inefficiency or whether it can be made async.

**Comment by jeremypw** [comment]
Looks like that plugin is re-parsing the document when it is refocused not just when it opens which seems excessive since it is unlikely the `.editorconfig` file has changed while unfocused. Closing a document focuses another one which triggers the plugin hooks.

**Comment by jeremypw** [comment]
Yes, I was thinking of monitoring the `.editorconfig` file.  The parsing should not be that onerous though for normal size documents so I am not sure this explains the slowness.

**Comment by jeremypw** [comment]
@aitor-gomila Could you confirm that the problem appears even if the only plugin enabled is `editorconfig` and disappears if that plugin is disabled?  I would ot expect that plugin to be so cpu or io hungry.

**Comment by jeremypw** [comment]
Also, is simply switching from one tab to another equally slow? That also triggers the plugin. Is closing an unmodified document as slow as closing a modified one?

**Comment by jeremypw** [comment]
@aitor-gomila I have pushed a draft PR #1334 for trying to address this issue.  At the moment it just makes the editorconfig plugin asynchronous.  If you are able to compile and install this PR to see whether it makes a difference to you that would help.  

If you know how to use `gdb` you could try running Code under `gdb` and press `<Ctrl>C` while the interface is frozen when closing a tab (use documents that are not valuable or are backed up).  You can then press `bt` to see which part of the code is running.  This is best done on code compiled from source with debug symbols.  The tabs close too quickly on my machine for me to do this.

**Comment by aitor-gomila** [comment]
Hi again. Yes, I can still reproduce, though now it is much better (freezes for an instant, maybe 0.25s). Maybe I had gotten a memory leak. It is more reproduceable when opening a large quantity of files (8) than a tiny quantitiy of files (2).

Do you think it would be feasible to create and maintain a plugin API?

**Comment by jeremypw** [comment]
I guess something could be put in the wiki.

I am looking into setting up a VM to emulate a slow cpu computer - if I succeed I hope to be able to locate bottlenecks more easily.

**Comment by aitor-gomila** [comment]
I am compiling your branch. How do you get `gtksourceview-4`?

**Comment by jeremypw** [comment]
you should be able to get the dependencies with `sudo apt build-dep io.elementary.code`

**Comment by aitor-gomila** [comment]
Thanks! Getting this now:
```vala
(io.elementary.code:5840): GLib-GIO-ERROR **: 21:45:36.243: Settings schema 'io.elementary.code.settings' does not contain a key named 'wholeword-search'
[1]    5840 trace trap  ./src/io.elementary.code
```

**Comment by jeremypw** [comment]
The message about settings suggests that you havent installed the application (`sudo ninja install`) and the settings schema differs from the version you are running.  Another setting must have been introduced since the last stable release so you need to install the new schema.

In answer to your `async` question my understanding is that it depends on whether it was called by an `async` process.  If it was not called by an `async` process and if it takes a long time itself or calls a blocking method (e.g. non-async i/o) then it is liable to block the UI.

**Comment by jeremypw** [comment]
Note: the open and close document methods are already async.  Even async methods can slow down the interface though if they hog the cpu.

**Comment by jeremypw** [comment]
I found things slow down considerably if memory is short because the computer is continually swapping things with the disk.  So you might want to check that.

**Comment by aitor-gomila** [comment]
I'm good at memory.
![Screenshot from 2023-06-17 11 19 46](https://github.com/elementary/code/assets/46191980/c484aa7c-eb82-4bad-9239-c90c21bce434)
These and others are not async. I'm convinced this specific method is not the cause, though.
![Screenshot from 2023-06-17 11 22 08](https://github.com/elementary/code/assets/46191980/ce1a36df-548e-4868-a04a-a04a2a36ec9e)

**Comment by kaixoo** [comment]
This is high priority

**Comment by kaixoo** [comment]
@jeremypw To keep the Git integration simple, why not simply create a button which brings up [Comet](https://appcenter.elementary.io/org.small_tech.comet/)? (or your configured default Git UI for commits).

For pulles/pushes and switching branches, we definitely will need our own UI.

**Comment by jeremypw** [comment]
There is already UI for switching branches in the sidebar context menu of ProjectFolders.  Could be made more discoverable though.
